import "server-only"
import fs from "node:fs/promises"
import type { Dirent } from "node:fs"
import path from "node:path"
import sharp from "sharp"
import { GENERAL_CATEGORY, type Material } from "./materials-shared"

export type { Material } from "./materials-shared"

/**
 * Marketing materials served straight out of `public/materials`.
 *
 * Adding artwork is a file drop — no code, no database, no upload UI. This
 * reads the folder and hands the dashboard gallery everything it needs to
 * render without layout shift: real pixel dimensions and a tiny inline blur
 * placeholder per image.
 *
 * CATEGORIES ARE FOLDERS. `public/materials/motivation/poster.jpg` shows up
 * under a "Motivation" tab; creating the folder is the entire act of creating
 * a category, which keeps the no-code promise above intact. Files left at the
 * root land in GENERAL. Only one level is scanned — deeper nesting is ignored
 * rather than silently flattened, so a stray folder can't scatter its contents
 * across the gallery.
 *
 * The listing is read on the server and the page has no dynamic inputs, so
 * Next prerenders it at build time: visitors pay nothing for the directory
 * scan or the sharp calls. New files therefore appear on the next deploy,
 * which is the same push that brings the files themselves.
 *
 * Display copies are generated by next/image (AVIF/WebP, resized per
 * viewport); the file under /materials stays untouched so the Download button
 * always hands over the original, full-quality asset.
 *
 * Images with genuine transparency (logo PNGs, say) are flagged `transparent`
 * so the gallery can sit them on a transparency checkerboard — a white mark on
 * a light tile, or a dark mark on the dark viewer, then stays legible when no
 * single flat backdrop would suit every logo. Opaque posters are left as-is.
 */

const MATERIALS_DIR = path.join(process.cwd(), "public", "materials")

/** Raster formats next/image can optimize. SVG is excluded deliberately: it is
 *  markup, and serving user-dropped SVG from our own origin is an XSS vector. */
const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif", ".gif"])

/** "materials1.jpg" → "Materials 1"; "top-seller_poster.png" → "Top Seller Poster". */
function humanize(fileName: string): string {
  const base = fileName.replace(/\.[^.]+$/, "")
  return (
    base
      .replace(/[-_]+/g, " ")
      // split "materials1" into "materials 1" so numbering reads naturally
      .replace(/([a-z])(\d)/gi, "$1 $2")
      .replace(/\s+/g, " ")
      .trim()
      .replace(/(^|\s)(\p{L})/gu, (_m, sep: string, c: string) => sep + c.toUpperCase()) || fileName
  )
}

/** Digit-aware sort so "materials2" precedes "materials10". */
const byName = new Intl.Collator("en", { numeric: true, sensitivity: "base" })

async function describe(file: string, dir: string): Promise<Material> {
  const absolute = path.join(MATERIALS_DIR, dir, file)
  const [stat, probe] = await Promise.all([
    fs.stat(absolute),
    // A corrupt or unreadable image must not take the whole gallery down —
    // it still lists and downloads, just without dimensions or a placeholder.
    // Fresh sharp instances per read so metadata/stats/resize never share a
    // pipeline; all three are one-time build-of-a-static-page costs.
    (async () => {
      try {
        const [meta, stats] = await Promise.all([sharp(absolute).metadata(), sharp(absolute).stats()])
        const lqip = await sharp(absolute).resize(16, 16, { fit: "inside" }).webp({ quality: 35 }).toBuffer()
        return {
          width: meta.width ?? null,
          height: meta.height ?? null,
          // isOpaque is false only when the alpha channel truly carries
          // transparent pixels, so a flattened PNG stays treated as a poster.
          transparent: stats.isOpaque === false,
          blurDataURL: `data:image/webp;base64,${lqip.toString("base64")}`,
        }
      } catch {
        return { width: null, height: null, transparent: false, blurDataURL: null }
      }
    })(),
  ])

  return {
    // Prefixed with the folder so two files can share a name across
    // categories without colliding as React keys.
    file: dir ? `${dir}/${file}` : file,
    src: dir
      ? `/materials/${encodeURIComponent(dir)}/${encodeURIComponent(file)}`
      : `/materials/${encodeURIComponent(file)}`,
    title: humanize(file),
    bytes: stat.size,
    category: dir ? humanize(dir) : GENERAL_CATEGORY,
    ...probe,
  }
}

/**
 * Every image in public/materials, sorted by name.
 *
 * Returns [] when the folder is missing so a fresh clone (or a deploy made
 * before anyone added artwork) renders the empty state instead of erroring.
 */
export async function listMaterials(): Promise<Material[]> {
  let entries: Dirent[]
  try {
    entries = await fs.readdir(MATERIALS_DIR, { withFileTypes: true })
  } catch {
    return []
  }

  const isImage = (name: string) => IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase())

  // Root-level files first, then each category folder in name order, so the
  // gallery's "All" tab reads in a stable, predictable sequence.
  const jobs: Array<Promise<Material>> = entries
    .filter((e) => e.isFile() && isImage(e.name))
    .map((e) => e.name)
    .sort(byName.compare)
    .map((name) => describe(name, ""))

  const dirs = entries.filter((e) => e.isDirectory()).map((e) => e.name).sort(byName.compare)
  for (const dir of dirs) {
    let inner: string[]
    try {
      inner = await fs.readdir(path.join(MATERIALS_DIR, dir))
    } catch {
      continue // unreadable folder shouldn't take the whole gallery down
    }
    for (const name of inner.filter(isImage).sort(byName.compare)) {
      jobs.push(describe(name, dir))
    }
  }

  return Promise.all(jobs)
}
