import "server-only"
import fs from "node:fs/promises"
import path from "node:path"
import sharp from "sharp"
import type { Material } from "./materials-shared"

export type { Material } from "./materials-shared"

/**
 * Marketing materials served straight out of `public/materials`.
 *
 * Adding artwork is a file drop — no code, no database, no upload UI. This
 * reads the folder and hands the dashboard gallery everything it needs to
 * render without layout shift: real pixel dimensions and a tiny inline blur
 * placeholder per image.
 *
 * The listing is read on the server and the page has no dynamic inputs, so
 * Next prerenders it at build time: visitors pay nothing for the directory
 * scan or the sharp calls. New files therefore appear on the next deploy,
 * which is the same push that brings the files themselves.
 *
 * Display copies are generated by next/image (AVIF/WebP, resized per
 * viewport); the file under /materials stays untouched so the Download button
 * always hands over the original, full-quality asset.
 */

const MATERIALS_DIR = path.join(process.cwd(), "public", "materials")

/** Raster formats next/image can optimize. SVG is excluded deliberately: it is
 *  markup, and serving user-dropped SVG from our own origin is an XSS vector. */
const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif", ".gif"])

/** "materials1.jpg" → "Materials 1"; "top-seller_poster.png" → "Top Seller Poster". */
function humanize(fileName: string): string {
  const base = fileName.replace(/\.[^.]+$/, "")
  return (
    base
      .replace(/[-_]+/g, " ")
      // split "materials1" into "materials 1" so numbering reads naturally
      .replace(/([a-z])(\d)/gi, "$1 $2")
      .replace(/\s+/g, " ")
      .trim()
      .replace(/(^|\s)(\p{L})/gu, (_m, sep: string, c: string) => sep + c.toUpperCase()) || fileName
  )
}

/** Digit-aware sort so "materials2" precedes "materials10". */
const byName = new Intl.Collator("en", { numeric: true, sensitivity: "base" })

async function describe(file: string): Promise<Material> {
  const absolute = path.join(MATERIALS_DIR, file)
  const [stat, probe] = await Promise.all([
    fs.stat(absolute),
    // A corrupt or unreadable image must not take the whole gallery down —
    // it still lists and downloads, just without dimensions or a placeholder.
    (async () => {
      try {
        const image = sharp(absolute)
        const { width, height } = await image.metadata()
        const lqip = await image.resize(16, 16, { fit: "inside" }).webp({ quality: 35 }).toBuffer()
        return {
          width: width ?? null,
          height: height ?? null,
          blurDataURL: `data:image/webp;base64,${lqip.toString("base64")}`,
        }
      } catch {
        return { width: null, height: null, blurDataURL: null }
      }
    })(),
  ])

  return {
    file,
    src: `/materials/${encodeURIComponent(file)}`,
    title: humanize(file),
    bytes: stat.size,
    ...probe,
  }
}

/**
 * Every image in public/materials, sorted by name.
 *
 * Returns [] when the folder is missing so a fresh clone (or a deploy made
 * before anyone added artwork) renders the empty state instead of erroring.
 */
export async function listMaterials(): Promise<Material[]> {
  let entries: string[]
  try {
    entries = await fs.readdir(MATERIALS_DIR)
  } catch {
    return []
  }

  const files = entries
    .filter((name) => IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase()))
    .sort(byName.compare)

  return Promise.all(files.map(describe))
}
